<?php
$ObjectManager= \Magento\Framework\App\ObjectManager::getInstance();
$context = $ObjectManager->get('Magento\Framework\App\Http\Context');
$isLoggedIn = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
?>

<?php if ($isLoggedIn): ?>
<div class="specialQuote">
    <div class="row mb32">
        <h5>SPECIAL QUOTE</h5>
    </div>
    <div class="field name">
        <form action=<?php echo $_SERVER['PHP_SELF'];?> method="post">
            <div class="control row">
                <input name="qty" id="qty" title="<?= $block->escapeHtmlAttr(__('Insert quantity')) ?>" class="input-text" type="text" data-validate="{required:true}" placeholder="Insert quantity"/>
                <button class="font12" name="specialQuote" type="submit">request</button>
            </div>
            <span class="font12">Requested Quantity*</span>
        </form>
        <?php
            if (isset($_POST['specialQuote'])) {
                $sent = $block->sendEmail($_POST['qty']);
                if($sent) {
                    echo 'Email has been sent to GS support';
                } else {
                    echo 'Could not send email. Try again.';
                }
            }
        ?>
    </div>
</div>
<?php endif; ?>