<?php
?>
<form class="" action="<?php echo $block->getBaseUrl().'manager/author/save'; ?>" id="author-test-form" method="post">
    <fieldset class="fieldset">
        <legend class="legend"><span>New Author</span></legend><br>
        <div class="field name">
            <label class="label" for="title"><span>Name</span></label>
            <div class="control">
                <input name="name" id="name" title="Name" value="" class="input-text" type="text">
            </div>
        </div>
        <div class="field books">
            <label class="label" for="books"><span>Books</span></label>
            <div class="control">
                <input name="books" id="books" title="Books" value="" class="number" type="text">
            </div>
        </div>
        <div class="field telephone">
            <label class="label" for="telephone"><span>Telephone</span></label>
            <div class="control">
                <textarea name="telephone" id="telephone" title="Telephone" class="input-text" cols="5" rows="3"></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="add" title="add" class="action add primary">
                <span>Add</span>
            </button>
        </div>
    </div>
</form>